### ISSUE TITLE
Idea: Rename config to theme

### ISSUE THREAD

**Issue by steida** [jxnblk/rebass#118]
I think it's more expressive and it's actually a theme. What do you think?

**Comment by jxnblk** [comment]
Config's not a great name, for sure. Personally I think `theme` is a loaded term and a bit different than the Rebass config, but I also realize it's becoming more common to refer to global styles as themes and have been considering renaming `config` to `theme`. The biggest issue is that `theme` is currently used as a prop to change color styles, and that change would require a major bump.

**Comment by steida** [comment]
There is nothing wrong with the major bump. Move fast and break things. The ecosystem needs it. Look at React Router 4, it's so much better. Look at how I am using rebass in https://github.com/este/este Soon I will need React Native rebass. Let's do it.

**Comment by steida** [comment]
https://github.com/este/este/blob/master/src/browser/app/themes/initial.js

**Comment by jxnblk** [comment]
I like react router but I also think it's a great example of why I'm cautious with major versions. I don't want to spend time updating router in a few things I'm using it in and don't know that I find the improvements that compelling at the moment. React's update cycle is a lot more pragmatic and I feel safer about using it in production because of that

**Comment by steida** [comment]
Nobody forces you to use a new version. RR4 is the game changer. Routes shall be collocated.
