### ISSUE TITLE
Passing `className` prop down to Rebass Component

### ISSUE THREAD

**Issue by benhowdle89** [jxnblk/rebass#137]
I wrap a `NavItem` in a custom Component, like so:

```
const MyLink = (props) => <NavItem style={styles} {...props} is={Link} />
export default MyLink
```

But if I pass down `className` in the props, like so:

```
<MyLink to="/settings" className="center py2 white bold caps h5" style={{
            backgroundColor: '#2ecc71'
        }}>Free trial account</MyLink>
```

The `className` values are not passed down to `NavItem`. Is this intended Rebass behaviour? Have I misinterpreted Rebass and this is not what I'm supposed to be doing?

**Comment by jxnblk** [comment]
Yes, that is currently intentional to help enforce style encapsulation in components. However, I have been considering allowing the `className` prop to be passed down for greater flexibility within Rebass.

For your example there are props that handle some of what I assume the classes are doing. E.g.

```js
<MyLink py={2} color='white' />
```

For the other styles, I would suggest encapsulating those in a wrapper component. For example:

```js
const WhiteCapsLink = (props) => <NavItem style={whiteCapsLinkStyles} />
```
