### ISSUE TITLE
Allow passing React elements to certain props

### ISSUE THREAD

**Issue by maxdeviant** [jxnblk/rebass#210]
I noticed that the `message` prop on `<Input />` only accepts a string. I'm sure there are other places where this is the case as well. I think it would be much more flexible if these instances could take React elements as well as strings.

Would you be in favor of easing up the PropTypes checks to allow passing React elements to these props?

This is important in particular for `react-intl`, where the idiomatic way of using translated messages is via the `<FormattedMessage />` component:

```js
<Input
  type='text'
  message={
    <FormattedMessage
      id='error'
      defaultMessage={`Whoops, that's an error.`}
      />
  }
  />
```

It can also be used for composing styles:

```js
<Input
  type='text'
  message={
    <strong>
      This field is required.
    </strong>
  }
  />
```

In fact, both of these use-cases *work* currently, but React complains about the PropTypes checks in development.

**Comment by maxdeviant** [comment]
I should add that I would be happily to submit PRs for this, perhaps on a component-by-component basis.

**Comment by theopak** [comment]
Hey @maxdeviant I agree that it would be helpful, and even valid, for PropTypes of certain fields to allow any react element instead of just strings. 

I opened this PR as a proof of concept for the `label` prop of an Input component: https://github.com/jxnblk/rebass/pull/194

Is this what you were thinking of? I think the `message` prop could benefit from the same change.

**Comment by maxdeviant** [comment]
@theopak Yep, this is exactly what I was referring to :smile:

**Comment by jxnblk** [comment]
The API has significantly changed in v1, where this shouldn't be an issue anymore

**Comment by maxdeviant** [comment]
@jxnblk v1 looks great, btw :tada:
