### ISSUE TITLE
PropTypes on Avatar saying imageUrl is required

### ISSUE THREAD

**Issue by RIP21** [jxnblk/rebass#263]
While it's actually src as in docs :) But PropTypes helper in WebStorm is saying that `imageUrl`.

Also, adding all styled-system PropTypes to all components will be neat, so it will show up all shortcuts etc. Maybe a bit overkill, but it will save typing a lot. Also helping understand what props is possible to be passed.
So for Row which type is Flex it will be nice to get PropTypes of Flex too. Trying out props praying that they will work is kind of weird :)

Thanks.

**Comment by jxnblk** [comment]
I don't know anything about *WebStorm* but all the prop types should be defined for Rebass's `hoc`, `grid-styled` components, and any custom props on Rebass components. I suspect it's an issue with the tool you're using, since tracking prop types can be tricky. Feel free to reopen this issue if you notice React prop types warnings behaving incorrectly though
