### ISSUE TITLE
Add height property shortcut

### ISSUE THREAD

**Issue by RIP21** [jxnblk/rebass#265]
Maybe it's more about `styled-system` than to `rebass` related. But adding `h` property will be helpful since we have width and it's kind of logical to have height too IMHO.
It will mean that we can control all dimensions which is cool.

It's nice for creating scrollable containers for example. 
When you create Column with particular width and some height and then you add `overflow-y: scroll` via overriding and you are ready to go. 
Not that override height is hard :) But sometimes you just need to limit height, and it's quite often.

If it's bad practice in styling, then tell me why and I will be smarter :)

**Comment by ferdinandsalis** [comment]
You can also extend an component to do just that yourself. However for symmetry it would be nice to have … 😊

**Comment by jxnblk** [comment]
Generally, you should avoid setting fixed heights on elements because it breaks the natural document flow, which can have bigger impacts when dealing with internationalization and translations, and can also cause issues with zooming in some cases. If you **do** want to control height, I recommend trying to use either `min-height` or flexbox if possible.

Since height is a property I rarely use, whereas width is used often, I don't think it makes sense to be a core prop in Rebass or Grid Styled. There's also a perf dent to adding more things like this in.

My recommendation is to extend a component, where you need it to control height. And, if you need height in a lot of places for whatever reason, you should look at styled-system's [`responsiveStyle`](https://github.com/jxnblk/styled-system#responsivestyle) function if you want a similar API to Rebass.

**Comment by RIP21** [comment]
@jxnblk thanks a lot for explanation.
 
About performance tho. I can see that Rebass components generate lot's of wrappers (they're not particularly create a div tho) creating extremely deep tree if you take a look at it in ReactDevTools.

Isn't that give a performance hit? And my view is quite basic, i'm scared to see what is going to be for a very big view. Also it's impossible to debug after all.

So it looks like that:
[Imgur](http://i.imgur.com/AbTFFA9.png)

**Comment by jxnblk** [comment]
Performance is something I really care about and want to ensure this gets better over time. The screenshot you linked to is the React component tree, which is different from the rendered HTML, and will look crazy whenever you introduce higher order components. The fact that Rebass uses HOC composition and that styled-components is itself a higher order component (with function calls in the opposite order) will surely make for a weird looking component tree, but that doesn't necessarily correlate with real world performance

**Comment by RIP21** [comment]
@jxnblk Thanks. It's exactly what I asked about.

And yes :) I know that SC does not necessarily create DOM elements, but just wraps it and inject to a className and then manage a set of them upon props change. And here is just a lot of layers of composition on one div etc.

BTW. `is='section'` prop is working on all components? Cause I tried on Flex and Box and it didn't work out. I can see `is` property rendered in the DOM element but it's still `div`. I suppose that from `div` it must become a `section` if I put `is='section'` respectively.
