### ISSUE TITLE
Container should have width=100%

### ISSUE THREAD

**Issue by karland** [jxnblk/rebass#271]
I believe the container should have `width=100%`. Otherwise it gets an auto width.

```JS
  {
    name: 'Container',
    type: 'div',
    props: {
      px: 3,
      ml: 'auto',
      mr: 'auto'
    },
    style: props => ({
      maxWidth: px(props.width || idx('maxWidth', props.theme) || 1024),
      width: 'auto'
    }),
    propTypes: {
      width: number
    }
},
```

**Comment by ferdinandsalis** [comment]
@karland as far as I can tell the `Container` components purpose is to constrain the weight of a component thus it has its width set to `auto`. If you pass in a width it will be its max width if you do not pass in width it will get it either from your theme or set it to 1024px. However granted it is bit confusing that the shorthand prop `w` does not render any effect whereas `width` does.

**Comment by karland** [comment]
@ferdinandsalis Thanks. I am not quite shure what you mean with

>constrain the weight of a component 

If you mean width, than your reasoning is the same even if width is set from auto to 100%.

**Comment by ferdinandsalis** [comment]
@karland I meant width of course 😊 What I meant to say is that this component does 'one' thing which is it contains (constrains) other things. Sorry if I confused you.

There is a difference of `auto` and `100%` — which I can not recall at the moment (something with margins) — but my guess the intent is to set the default value for width.

**Comment by jxnblk** [comment]
The default value for width is `auto`; in the case of block-level elements that is usually 100%. There are only a few cases where that isn't true, but allowing developers to take advantage of that are in the interest of this library, in my opinion – that is, I'm taking the approach of not adding opinionated styles instead of applying heavy-handed CSS. And, if you explicitly need `width: 100%`, you can extend a component using styled-components
