### ISSUE TITLE
Is property doesn't work correctly on Box and Flex and maybe others.

### ISSUE THREAD

**Issue by RIP21** [jxnblk/rebass#277]
is='section' prop is working on all components? Cause I tried on Flex and Box and it didn't work out. I can see this attribute rendered in the DOM element but it's still div. I suppose that from div it must become a section if I put is='section' respectively.

Here is an example:
[![Edit 3lGBGv6An](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3lGBGv6An)

If take a look at iframe they are still divs, but with `is` attribute only, which is, from what I know, not a valid attribute.

If I'm wrong, please clarify on that a bit.
Thanks.

**Comment by jxnblk** [comment]
From a technical perspective, the reason the `is` prop does not work on Box and Flex, is because they don't use the [tag](https://github.com/jxnblk/rebass/blob/master/src/tag.js) function for the underlying component. I'd like to update the Grid Styled library to support this, but for the time being you can alway nest elements when needed

**Comment by jxnblk** [comment]
I've abstracted out the tag higher order component to use in Rebass and Grid Styled here: https://github.com/jxnblk/tag-hoc and will likely use this in conjunction with styled-components until styled-components/styled-components#439 is resolved (related: #266)

**Comment by jxnblk** [comment]
This should be fixed in #283 now
