### ISSUE TITLE
Managing fontSizes

### ISSUE THREAD

**Issue by andyford** [jxnblk/rebass#396]
This is definitely a question and not a bug... I'm new to Rebass (and styled-system) and I want to make sure I'm understanding how to use fontSizes properly.

Specifically if I have a custom array of fontSizes like [12, 14, 16, 18, 21] and I want to use the size at index 3, then I use the prop fontSize={3}, but what if I need to add another font size between index 1 and 2? like [12, 14, 15, 16, 18, 21] ... Now my array is off... or am I missing something?

It feels very abstract to use fontSize={3} to get an actual font-size of 18px for example (and it gets more abstract with media queries). Is there a supported different way to approach this? Perhaps named sizes like fontSize="large" or something?

Thanks!

**Comment by andyford** [comment]
I discovered that it's possible to redefine the fontSizes theme array as an object instead.

```
fontSizes: {
        'tiny': '10px',
        'medium': '14px',
        'large': '16px',
    },
```

^ this works, and you can even use it on component props with media queries like `fontSize={['tiny', 'large']}` 

To me, this is a more human readable abstraction BUT... there's no guarantee (that I'm aware of) that the library will always support this.  And any default components which don't have any custom font size overrides, end up with font-size 1px.

**Comment by jxnblk** [comment]
As you've discovered, for any of the array values in the theme, you can use an object instead, and styled-system will support objects for the foreseeable future. In the end it's checking for keys in the theme objects and falling back to raw values if the key doesn't exist in the theme.

WRT:
> but what if I need to add another font size between index 1 and 2?

That's an intentional limitation/constraint of using a strict type scale. If you change the scale in your app, that should be considered a breaking change.

Closing this for now, but feel free to open another issue if needed

**Comment by lbineau** [comment]
@andyford Have found any solution working not to have the default component with a decent font-size ?

**Comment by andyford** [comment]
@lbineau I just don't use Rebass fontSizes any more 🤷

**Comment by andyford** [comment]
Ah I see that using objects is now officially documented in the awesome underlying styled-system docs https://styled-system.com/responsive-styles/#using-objects

I'm working on a new project using styled-system (without Rebass) and it's comforting to see this in the official docs. Thanks, @jxnblk!
