### ISSUE TITLE
Use children instead of steps prop for SequenceMap

### ISSUE THREAD

**Issue by phated** [jxnblk/rebass#40]
Would you be open to a component called `Step` (or something similar) that can be used as children to `SequenceMap` instead of a `steps` property with a custom DSL?

**Comment by jxnblk** [comment]
Absolutely. This is one area where I've struggled defining the API on UI components. In the case of SequenceMap, you probably wouldn't want to use a `Step` component all on its own, but it can be nice to more declaratively use the inner parts.

I think this would actually be super easy to support both approaches, since the objects in the steps array are just the child components' props. Naming-wise, I think having it be a subcomponent like `SequenceMap.Step` is nice because it shows the implied relationship.

**Comment by phated** [comment]
Yeah, I think the namespace works well, especially for people that use ES2015 imports: e.g. `import SequenceMap, { Step } from 'rebass/SequenceMap'`

**Comment by jxnblk** [comment]
Version `0.2.3` now supports both the `steps` prop and children subcomponents.

You can import the subcomponent two ways:

```js
import { SequenceMap, SequenceMapStep } from 'rebass'
```
*or*
```js
import { SequenceMap } from 'rebass'

// ...
<SequenceMap>
  <SequenceMap.Step />
</SequenceMap>
```

For use as a subcomponent, it would look something like this:

```jsx
<SequenceMap>
  <SequenceMap.Step active href='#foo' children='Foo' />
  <SequenceMap.Step href='#bar' children='Bar' />
</SequenceMap>
```
