### ISSUE TITLE
Input has no border

### ISSUE THREAD

**Issue by akarienta** [jxnblk/rebass#440]
I am using a simple `Input` component like it is described in a doc:

```jsx
<Input
  defaultValue='Hello'
  placeholder='Input'
/>
```

However, there is no border even if I specify it with `border` prop. Browser inspector shows it is set to `0` in every case. I checked everything and I am pretty sure I am not overriding it. Tested in last the Chrome. Is it a bug?

**Comment by jxnblk** [comment]
The Input uses box-shadow for styles. If you're not seeing the box-shadow, make sure you have the Rebass Provider component somewhere at the root of you application

**Comment by akarienta** [comment]
I have it, it has store property but I guess it doesn't matter.

**Comment by akarienta** [comment]
Ah ok, you need a specific provider from `rebass` package, makes sense. Maybe you can add it to doc.

```jsx
import { Provider } from 'react-redux';
import { Provider as ThemeProvider } from 'rebass';
```

**Comment by bbenne10** [comment]
This is still wildly unclear in the docs. I'm using a `ThemeProvider`, so that's not my issue. The documentation mentions that the `Input` component accepts a `border` and `borderColor` prop, but those seem to be blacklisted? (I'm not 100% sure on what that means - whether it's "silently blacklist this component from accepting this prop" or "don't pass this on to the DOM component I'm going to build")

Why is `border` documented in the docs if it uses `boxShadow` exclusively? This seems to be a wider issue with the documentation but this instance has made me particularly frustrated...

**Comment by mattietea** [comment]
What is the reasoning behind not allowing a border?

**Comment by taylonr** [comment]
@bbenne10 are you using the `ThemeProvider` from Rebass? I had a `ThemeProvider` but it was the one from `styled-components` instead. Once I replaced it with the one from Rebass everything worked.

**Comment by bbenne10** [comment]
@taylonr: I am following the guidelines [here](http://jxnblk.com/rebass/getting-started).

```javascript
import { ToastContainer } from 'react-toastify'
import { Provider as ThemeProvider } from 'rebass'
import React from 'react'
import ReactDOM from 'react-dom'
import { Provider } from 'react-redux'
import { ConnectedRouter } from 'connected-react-router'

import { AuthWrapper } from './components/auth'
import { history, store } from './store'

ReactDOM.render(
  <ThemeProvider>
    <Provider store={store}>
      <React.Fragment>
        <ToastContainer autoClose={4000} />
        <AuthWrapper>
          <ConnectedRouter history={history}>
            <Switch>
              {/*<Routes />*/} 
            </Switch>
          </ConnectedRouter>
        </AuthWrapper>
      </React.Fragment>
    </Provider>
  </ThemeProvider>,
  document.getElementById('root')
)

if (module.hot) {
  module.hot.accept(function () {})
}
```
